apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-loki-cert
  namespace: loki-grafana-stack
spec:
  secretName: grafana-loki-tls
  dnsNames:
    - grafana-loki.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
